task 9: demo web app
sgol13/elixir-chatbot pull request #12
Opened 2023-06-25 09:38 UTC by sgol13

If you want to review, just look at the second commit. The first commit contains only auto-generated code from Phoenix framework.

2023-06-27 14:58 UTC, karol-t-wilk requested changes
I think this looks good aside from some minor things regarding convention in Elixir. Great job!

2023-06-27 22:53 UTC, sgol13 commented on apps/chat_web/lib/chat_web/live/chat_live.ex
> +  end
Good idea, I created a struct for that

2023-06-27 22:53 UTC, sgol13 commented on apps/chat_web/lib/chat_web/live/chat_live.ex
> +      end
I changed to this convention, thank you. Much cleaner now

2023-06-28 12:49 UTC, karol-t-wilk approved these changes

2023-06-28 15:46 UTC, merged